// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:390f1662-25fc-4e07-9977-21211dc915d0",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_4KO8zN0Yy",
    "aws_user_pools_web_client_id": "1rkp83ee1s9rk2eln6tuaauhen",
    "aws_content_delivery_bucket": "aws-amplify-example",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "https://dzjmxdfuuwmc6.cloudfront.net"
};


export default awsmobile;
